### PR TITLE
Window flags, pref paths, ticks/time, new keyboard

### PR DESCRIPTION
**Pull request by genericptr**

### CODE REVIEW

**Comment by daar** [comment]
Thanks fort the patch! Here and there it needs some work and testing, but I’m excited with the basic foundation layed out.

**Comment by genericptr** [comment]
Great, I thought you abandoned the project. Btw the latest version of macOS (Mojave) totally broke the OpenGL support (which I fixed) so I need merge those changes also. The frame rate is now running at maximum unless I use a sleep call so I think they broke vsynch also but I haven’t fixed that. Now that you mentioned it GLPT doesn’t have an option to enable vsynch or not so I guess the other platforms are just assumed to run at no more than 60 fps.

> On Feb 19, 2019, at 3:33 PM, daar <notifications@github.com> wrote:
> 
> Thanks fort the patch! Here and there it needs some work and testing, but I’m excited with the basic foundation layed out.
> 
> 

Regards,
	Ryan Joseph

**Comment by daar** [comment]
Hi Rian,

No not abandoned at all! Sorry though it took me so long to apply the patch. I recently bought a new house so that’s taking up some time. I will try to keep everything more up to date from now. I will also give you commit rights for the project.

Make any modifications that you see fit, as long as they fit within the design concept of GLPT.

Rgds Darius 

Verstuurd vanaf mijn iPhone



Verstuurd vanaf mijn iPhone
> Op 19 feb. 2019 om 19:16 heeft genericptr <notifications@github.com> het volgende geschreven:
> 
> Great, I thought you abandoned the project. Btw the latest version of macOS (Mojave) totally broke the OpenGL support (which I fixed) so I need merge those changes also. The frame rate is now running at maximum unless I use a sleep call so I think they broke vsynch also but I haven’t fixed that. Now that you mentioned it GLPT doesn’t have an option to enable vsynch or not so I guess the other platforms are just assumed to run at no more than 60 fps.
>

**Comment by daar** [comment]
Something went wrong last week with merging the pull request.

**Pull request merged**
